---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/23 16:30
---


local http = require("socket.http")
result = http.request("http://anhuaxiang.cn")
print(result)
print("*****************************************************************************************")

local socket = require("socket")
local host = "www.baidu.com"
local file = "/"
local sock = assert(socket.connect(host, 80))
sock:send("GET " .. file .. " HTTP/1.0\r\n\r\n")
repeat
    local chunk, status, partial = sock:receive(1024)
    print(chunk or partial)
    print("------------------")
until status ~= "closed"
sock:close()

